In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

corpus = ['dog', 'cat', 'dog', 'fish']

corpus = np.array(corpus).reshape(-1, 1)

onehot_encoder = OneHotEncoder(sparse_output=False)
onehot_encoder = onehot_encoder.fit_transform(corpus)

print(onehot_encoder)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import spacy
import numpy as np

nlp = spacy.load("en_core_web_sm")

V = "first dog name his second he third one And Is the this my"

doc = nlp(V)
tokens = [(token.text, token.is_stop) for token in doc]
print(tokens)


doc = V.split()
doc = np.array(doc).reshape(-1, 1)

onehot_encoder = OneHotEncoder(sparse_output=False)
onehot_encoder = onehot_encoder.fit_transform(doc)

print(onehot_encoder)



[('first', True), ('dog', False), ('name', True), ('his', True), ('second', False), ('he', True), ('third', True), ('one', True), ('And', True), ('Is', True), ('the', True), ('this', True), ('my', True)]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [3]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'my name is the first dog',
    'his name is the second dog',
    'and he is the third one',
    'is this the first dog?',
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(corpus)

print(X.toarray())
print(vectorizer.get_feature_names_out())





[[0 1 1 0 0 1 1 1 0 0 1 0 0]
 [0 1 0 0 1 1 0 1 0 1 1 0 0]
 [1 0 0 1 0 1 0 0 1 0 1 1 0]
 [0 1 1 0 0 1 0 0 0 0 1 0 1]]
['and' 'dog' 'first' 'he' 'his' 'is' 'my' 'name' 'one' 'second' 'the'
 'third' 'this']


In [ ]:
import spacy
from sklearn.preprocessing import OneHotEncoder
import numpy as np

def BagofWord(input):
    sentences = []
    nlp = spacy.load("en_core_web_sm")
    input = input.split('.')

    for senten in input:
        sen = nlp(senten)
        for temp in sen.ents:
            sentences.extend(temp)
    for sen in sentences:
        print(sen)
    

BagofWord("My name is the first dog. His name is the second dog, and he likes fish. Is this the first dog?")

M
y
 
n
a
m
e
 
i
s
 
t
h
e
 
f
i
r
s
t
 
d
o
g
 
H
i
s
 
n
a
m
e
 
i
s
 
t
h
e
 
s
e
c
o
n
d
 
d
o
g
 
a
n
d
 
h
e
 
l
i
k
e
s
 
f
i
s
h
 
I
s
 
t
h
i
s
 
t
h
e
 
f
i
r
s
t
 
d
o
g
?
